# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afda1323b99c376fc1633351d4352a2b2683897afd2927e6256a08e061204a190335cb071d46c2d3ebfb9161cec7d30dda7528b91e06e5be9cc1bc6cb41f15f5

test:
  secret_key_base: f712ac245829770d1b19329af30a915ef4d1dfcc3a3050829f418d292d108b8d05729c9bf6dfa1d0d75253e6289722f1dc5c04cd091a0fd1ac9de2e121dbe91b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
